{% set name = "asciistuff" %}
{% set version = "1.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asciistuff-{{ version }}.tar.gz
  sha256: 1ea328da280888c721e4ed4e96001720bb3e2520864d6cc3a98cd4fbe7e03233

build:
  noarch: python
  number: 0
  entry_points:
    - asciistuff = asciistuff:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - colorama
    - cowpy
    - pillow
    - pyfiglet
    - python >=3.6
    - termcolor
    - terminaltables

test:
  imports:
    - asciistuff
  commands:
    - pip check
    - asciistuff --help
  requires:
    - pip

about:
  home: https://github.com/dhondta/python-asciistuff
  summary: Library for producing ASCII arts from a text or an image
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
