{% set name = "asciistuff" %}
{% set version = "1.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/asciistuff-{{ version }}.tar.gz
  sha256: 7c220d156da4977e80eec324fc21a8ecba8d8681f59d415909e05506befacf1d

build:
  noarch: python
  number: 1
  entry_points:
    - asciistuff = asciistuff:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm
  run:
    - colorama
    - cowpy >=1.1.2
    - pillow >=10.2.0
    - pyfiglet
    - python >={{ python_min }},<4.0
    - termcolor
    - terminaltables

test:
  imports:
    - asciistuff
  commands:
    - pip check
    - asciistuff --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dhondta/python-asciistuff
  summary: Library for producing ASCII arts from a text or an image
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
