schema_version: 1

context:
  name: asciistuff
  version: 1.3.3

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/asciistuff-${{ version }}.tar.gz
  sha256: d4d1408512fa792bd50c3e7064bc39c29895a4678b8013d705b526d6b85cf07e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - asciistuff = asciistuff:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools >=70.0
    - setuptools-scm
  run:
    - colorama
    - cowpy >=1.1.5
    - pillow >=11.2.0
    - pyfiglet >=1.0.3
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - asciistuff
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - asciistuff --help

about:
  summary: Library for producing ASCII arts from a text or an image
  license: GPL-3.0-or-later
  license_file: LICENSE
  homepage: https://github.com/dhondta/python-asciistuff

extra:
  recipe-maintainers:
    - thewchan
